### ISSUE TITLE
Update the version of Newtonsoft.Json

### ISSUE THREAD

**Issue by Flavien** [MetacoSA/NBitcoin#169]
I'm seeing conflicts between the version referenced by NBitcoin (Newtonsoft.Json 6.0.1) and the one some other libraries are using (Microsoft.Extensions.Configuration.Json uses Newtonsoft.Json 9.0.1).

It would be great to upgrade to the latest version to avoid these.

**Comment by NicolasDorier** [comment]
yep, will do it. Normally, if you use 9.0.1, NBitcoin should still work fine though. (despite warning)
Can you confirm ?

**Comment by Flavien** [comment]
I think it does, but can't try as I get an exception if I reference it. I am still debugging, not sure what the exact issue is (using .NET Core 1.0).

**Comment by NicolasDorier** [comment]
I've not used .NET Core 1.0 yet, I'm interested about problems you get.
Anyway, I want to completely remove dependency on Newtonsoft by including into NBitcoin the strict subset of the lib I am using. It will make porting easier.

**Comment by NicolasDorier** [comment]
@Flavien I tried to remove dependency to newtonsoft, but the work is too big. Have you found out exactly what is the exception you get ?

**Comment by Flavien** [comment]
@NicolasDorier You don't need to remove the dependency. Just upgrading to 9.0.1 would fix the issue.

The exception I am getting is:

```
An exception of type 'System.IO.FileLoadException' occurred in Microsoft.Extensions.Configuration.UserSecrets.dll but was not handled in user code

Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by Flavien** [comment]
This happens because I have a reference to ``Microsoft.Extensions.Configuration.Json`` which requires 9.0.1.

**Comment by NicolasDorier** [comment]
have you tried binding redirects ?

**Comment by NicolasDorier** [comment]
I'm not against upgrading, but I fear breaking something. This is a big version number, so API should have broke. After update, my users might see old code which worked suddenly fail.

But I guess I'll need to do it...

**Comment by Flavien** [comment]
Apparently, binding redirects no longer exist in .NET Core: https://github.com/aspnet/Home/issues/407#issuecomment-85545103

**Comment by NicolasDorier** [comment]
but in this case what will happen if another lib use version 8.0.0.0  and not 9.0.0.0 ? does .NET Core use http://semver.org/ "backed in" ?

**Comment by NicolasDorier** [comment]
I updated NBitcoin and Newtonsoft, let me know if it solved

**Comment by Flavien** [comment]
It doesn't seem to work. Also [NuGet](https://www.nuget.org/packages/NBitcoin/) still shows 6.0.1.

**Comment by NicolasDorier** [comment]
Fixed it

**Comment by NicolasDorier** [comment]
Fixed now

**Comment by NicolasDorier** [comment]
have you tried ? is it better ?

**Comment by Flavien** [comment]
I still get the same error, it doesn't seem that the problem was coming from NBitcoin since you are now on the same version.

**Comment by Flavien** [comment]
Ok, I found a problem: in 3.0.0.37, the version targeting ``portable-net45+win+wpa81+Xamarin.iOS10+MonoAndroid10+MonoTouch10`` (Profile111) is still referencing 6.0.0.0 instead of 9.0.0.0.

**Comment by NicolasDorier** [comment]
mmh je problem is that portable-net45+win+wpa81+Xamarin.iOS10+MonoAndroid10+MonoTouch10 is not referencing a package, but a "home grown" newtonsoft that could compile under this profile :(
(Newtonsoft is not available for Profile111)
Have you tried to check what happen with NBitcoin.Mono ?

If it is still problematic I guess that I'll need to release a specific parckage for .NET Core.

**Comment by Flavien** [comment]
So I managed to make it work by changing:

```
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
```

into:

```
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win+wpa81+wp80+Xamarin.iOS10+MonoAndroid10+MonoTouch10"
      ]
    }
  },
```

But, yes, you should consider publishing a version targetting ``netstandard`` since this will be replacing PCLs.

**Comment by NicolasDorier** [comment]
I want to cleanup my current nuget mess. This is good opportunity.
Also since there is shared project from VS 2015, there is now easier way to do than the MSBuild hacks I used.

PCLs are becoming obsolete ?
So what a complete lib should release ? Mono, Windows, and Core ?

**Comment by jcansdale** [comment]
> But, yes, you should consider publishing a version targetting netstandard since this will be replacing PCLs.

@Flavien Thanks for the link. PCLs always baffled me. I'm glad it's being simplified. :smile:

**Comment by NicolasDorier** [comment]
@Flavien problem should be solved, I integrated Newtonsoft inside the NBitcoin portable project, so there should be no conflict anymore.

**Comment by tom-corwin** [comment]
@jcansdale I am working on a netstandard version of this in issue #176
