### ISSUE TITLE
Referencing incorrect version of Net.Sockets.

### ISSUE THREAD

**Issue by kyluke** [MetacoSA/NBitcoin#181]
Hey MetacoSA!

I am currently working with your awesome library and have a few of my modules out of the way already. I am currently working on trying to push transactions built by NBitcoin to a Node of mine. However, whenever I try to run it, specifically with "Using NBitcoin.Protocol", it seems to be referencing an incorrect version of System.Net.Socket. 

As You can see from the screenshot below, I do have the correct version installed. Now I know this may not be related to anything in your library but I cannot seem to find a way to resolve this. Any ideas?

`Error CS1705: Assembly 'NBitcoin, Version=3.0.0.46, Culture=neutral, PublicKeyToken=null' depends on 'System.Net.Sockets, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version number than referenced assembly 'System.Net.Sockets, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' (CS1705) (qcan.iOS)`

<img width="294" alt="bildschirmfoto 2016-08-11 um 16 57 52" src="https://cloud.githubusercontent.com/assets/1087345/17593082/089a20ec-5fe5-11e6-8fc6-ee3460032226.png">

**Comment by NicolasDorier** [comment]
thanks for the report, .NET Core support has been added recently to NBitcoin, so definitively some guinea pigs.

Can I ask you your plateform ?

**Comment by NicolasDorier** [comment]
Ok, I checked a bit in the problem. Can you remove your reference to System.Net.Socket and reinstall NBitcoin's package ? Normally it will reference the 4.1.0 (for .NET standard 1.6)

**Comment by kyluke** [comment]
Hi Nicolas

Thanks for your quick reply! I have removed NBitcoin and System.Net.Sockets from my project (uninstalled), which forced me to uninstall NetStandard.Library as well.

I then cleaned the project, closed my IDE (Xamarin Studio) and reopened it again, reinstalled NBitcoin (3.0.0.46), which then installed NetStandard.Library 1.6.0 again as well as System.Net.Sockets 4.1. However, the problem persists.

I am running this using Xamarin and therefore Mono. I see there is a specific NBitcoin package for mono but I couldn't install it due to this error message:

Could not install package 'NBitcoin.Mono 3.0.0.46'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I am using Xamarin Studio with Xamarin and therefore Mono. I hope this helps? Let me know if you need more information.

**Comment by NicolasDorier** [comment]
@kyluke thanks, can you try doing it again ? I pushed 3.0.0.47 which target .NETStandard1.3 instead of 1.6 and it uses System.Net.Sockets, Version=4.0.0.0 .

Reference NBitcoin, not NBitcoin.Mono.

**Comment by NicolasDorier** [comment]
With 3.0.0.47, it should work. I think your problem boils down that you are using old version of xamarin which use .NETStandard1.3. However, NBitcoin is able to target .NETStandard1.3 without missing features so now it should work even if you don't update xamarin. Please let me know.

**Comment by kyluke** [comment]
Hi Nicolas

Thank you very much. I removed the older library and reinstalled it but am still facing the same problem

	CSC: error CS1705: Assembly `NBitcoin, Version=3.0.0.47, Culture=neutral, PublicKeyToken=null' depends on `System.Net.Sockets, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version number than referenced assembly `System.Net.Sockets, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Any ideas on whether this is an issue on my side now?

**Comment by NicolasDorier** [comment]
I don't think it is an issue on your side, I'm trying to replicate the issue.

**Comment by NicolasDorier** [comment]
.NETStandard1.3 references also 4.1.0.0 indeed :(
Can you try Update-Package System.Net.Sockets ? if it works, can you then update Xamarin, recreate a project like you did, and verify 4.1.0.0 is referenced correctly ?

**Comment by NicolasDorier** [comment]
wait my fault, something is wrong with my package.

**Comment by NicolasDorier** [comment]
I could reproduce the problem working on it...

**Comment by kyluke** [comment]
Hi Nicolas

Thank you very much. I appreciate your time on this :)

**Comment by NicolasDorier** [comment]
@kyluke after banging my head, I noticed that Xamarin on Visual Studio does not have this problem.

It seems that xamarin support standard library very recently (3 aug), and has been only supported on xamarin on visual studio for now.
So for now, you can't use the Node classes in a IOS project compiled on mac. (a normal console application on mac would work though)

If you want still to broadcast your transaction, try to use my library QBitNinja.Client (this is a block explorer, and I allow sending transactions through it)

**Comment by kyluke** [comment]
Hi Nicolas

Thank you very much for investigating this. I appreciate it. I will contact Xamarin and find out what the delay in releasing the newer version for Xamarin on the mac is.

Once they have released the update, I will work on submitting to the node, we currently have a work around to keep us going for now.

Thanks again for your assistance!

**Comment by NicolasDorier** [comment]
@kyluke can you keep the issue open ? They say 6.0.2 should allow consumption of standard lib https://blog.xamarin.com/net-standard-library-support-for-xamarin/ what is your version ?

**Comment by kyluke** [comment]
@NicolasDorier I'll check that out and provide some feedback a little bit later. Thanks for that :)

**Comment by NicolasDorier** [comment]
Verified on my laptop, I have 6.0.2, I filed a bug https://bugzilla.xamarin.com/show_bug.cgi?id=43305

**Comment by NicolasDorier** [comment]
They confirmed it was a bug: "Fixed in master and Mono 4.6". I don't know if that mean we need to wait or can do something about it now, they have not even linked the commit. :(

**Comment by NicolasDorier** [comment]
You can try to go on the alpha channel and update your xamarin so it uses Mono 4.6.

**Comment by kyluke** [comment]
@NicolasDorier you are a very thorough man! I see, they are lagging behind the release for xamarin on mono. I will test this out and get back to you. It's not ideal to switch to an alpha channel as this is a product intended for public use. Instabilities elsewhere are not something that we would like to introduce.

That being said, I'll test it and see where it takes me. Hopefully Xamarin doesn't take too long to release a newer version. Any ideas on who to contact at Xamarin for updates on this?

Thanks again @NicolasDorier, you have been incredibly helpful.

**Comment by NicolasDorier** [comment]
@kyluke yes, you need to contact those guys: https://bugzilla.xamarin.com/show_bug.cgi?id=43305
I tried to ask them what to do for now, but they still have not responded to me. :(

**Comment by NicolasDorier** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=43305

```
You install Mono 4.6 preview (e.g. by switching to alpha channel in XS)
```

**Comment by NicolasDorier** [comment]
@kyluke if you have other weird bug coming from NBitcoin since I updated to netstandard, check https://github.com/MetacoSA/NBitcoin/issues/188 . Basically you need to modify csproj to use netstandard1.1 instead of 1.3 because of some other xamarin bug. :(

**Comment by kyluke** [comment]
@NicolasDorier shot for the heads up! Going to update now and check it out.

**Comment by NicolasDorier** [comment]
It was fixed in the latest stable version of xamarin! yay! (tested)
